/*
  Auto-generated by Spline
*/
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/fHSFs1CucN88MZIU/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#42496f']} />
      <group {...props} dispose={null}>
        <mesh
          name="Blob 2"
          geometry={nodes['Blob 2'].geometry}
          material={materials['Blob 2 Material']}
          castShadow
          receiveShadow
          position={[-144, -577.68, -2121.64]}
          rotation={[-0.02, 0, 0]}
        />
        <mesh
          name="Blob 1"
          geometry={nodes['Blob 1'].geometry}
          material={materials['Blob 1 Material']}
          castShadow
          receiveShadow
          position={[-57, -678.5, -905.98]}
        />
        <group name="UI" position={[-40, -663.5, 105.4]} rotation={[-0.7, 0.7, 0.7]}>
          <mesh
            name="Avatar"
            geometry={nodes.Avatar.geometry}
            material={materials['Avatar Material']}
            castShadow
            receiveShadow
            position={[516.14, 273.8, -40]}
          />
          <mesh
            name="New Member 4"
            geometry={nodes['New Member 4'].geometry}
            material={materials['New Member 4 Material']}
            castShadow
            receiveShadow
            position={[518.04, -151.25, -40]}
          />
          <mesh
            name="New Member 3"
            geometry={nodes['New Member 3'].geometry}
            material={materials['New Member 3 Material']}
            castShadow
            receiveShadow
            position={[518.04, -84.25, -40]}
          />
          <mesh
            name="New Member 2"
            geometry={nodes['New Member 2'].geometry}
            material={materials['New Member 2 Material']}
            castShadow
            receiveShadow
            position={[517.04, -17.25, -40]}
          />
          <mesh
            name="New Member 1"
            geometry={nodes['New Member 1'].geometry}
            material={materials['New Member 1 Material']}
            castShadow
            receiveShadow
            position={[518.04, 49.75, -40]}
          />
          <mesh
            name="Popular Card 1"
            geometry={nodes['Popular Card 1'].geometry}
            material={materials['Popular Card 1 Material']}
            castShadow
            receiveShadow
            position={[-137.19, -249.25, -40]}
          />
          <mesh
            name="Popular Card 2"
            geometry={nodes['Popular Card 2'].geometry}
            material={materials['Popular Card 2 Material']}
            castShadow
            receiveShadow
            position={[211.04, -249.75, -40]}
          />
          <mesh
            name="Featured Card 1"
            geometry={nodes['Featured Card 1'].geometry}
            material={materials['Featured Card 1 Material']}
            castShadow
            receiveShadow
            position={[-135.96, -0.25, -40]}
          />
          <mesh
            name="Featured Card 2"
            geometry={nodes['Featured Card 2'].geometry}
            material={materials['Featured Card 2 Material']}
            castShadow
            receiveShadow
            position={[211.04, -1.25, -40]}
          />
          <mesh
            name="Banner"
            geometry={nodes.Banner.geometry}
            material={materials['Banner Material']}
            castShadow
            receiveShadow
            position={[36.54, 263.89, -40]}
          />
          <mesh
            name="Daccord"
            geometry={nodes.Daccord.geometry}
            material={materials['Daccord Material']}
            castShadow
            receiveShadow
            position={[0, 0, -52.4]}
          />
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-5000}
          shadow-camera-right={5000}
          shadow-camera-top={5000}
          shadow-camera-bottom={-5000}
          position={[107.56, -598.15, 2565.63]}
          scale={[1, 1, 8.58]}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.66}
          far={100000}
          near={-100000}
          position={[-46.6, -682.16, -165.22]}
          rotation={[0, 0, 0]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}

 {/* <Wrapper>
        <Spline
          className='spline'
          scene="https://prod.spline.design/fHSFs1CucN88MZIU/scene.splinecode"
          style={{ position: "absolute", top: 0, left: 0, zIndex: 0 }}
        />
        </Wrapper> */}

// const Wrapper = styled.div`
//   font-size: 16px;
//   text-align: center;
//   color: palevioletred;
//   position: relative;
  
//   .spline{
//     position: absolute;
//     margin : 10;
//   }

// `;

// import Spline from '@splinetool/react-spline';
// import styled  from 'styled-components';